### ISSUE TITLE
window_size

### ISSUE THREAD

**Issue by jtlz2** [tinankh/GOD#1]
Thank you for making available such brilliant code!

`GOD` requires a `window_size`, but no reference is made to it in the paper. Are you able to give any advice on how to select it?

- Is it a "tunable parameter" or do you not consider it a hyperparameter of the algorithm?
- Is the idea to run at different `window_size`s and compare the outputs?
- How does processing time scale with `window_size` (badly at small values, it seems)?

Do you have any standard test images available?

Do you have any downstream / sample code or test data demonstrating the results from subsections (B) and (C) from your section (IV)?

Thanks again and Happy Christmas

**Comment by tinankh** [comment]
Thank you for your interest in my code. 
Soon a detailed paper will be published where all your questions will hopefully be answered: https://www.ipol.im/pub/pre/283/
